base_url: http://www.consultant.ru/
articles_info_file: resources/articles_info.csv
model_info_file: resources/212.zip
articles_vectors_info_file: resources/articles_vectors_info_file_with_words.csv
articles_frequency_info_file: resources/articles_frequency_info_file.csv
articles_frequency_info_file_with_constraint: resources/articles_frequency_info_file_with_constraint.csv
articles_unique_words_analysis_file: resources/articles_unique_words_analysis_file.csv
articles_unique_words_info_file: resources/articles_unique_words_info_file.csv
articles_unique_words_analysis_file_with_frequency: resources/articles_unique_words_analysis_file_with_frequency.csv
most_popular_words_analysis_file: resources/most_popular_words_analysis_file.csv
unique_words_in_articles_analysis_file: resources/unique_words_in_articles_analysis_file.csv
information_about_target_words: resources/information_about_target_words.csv
information_about_target_words_with_links: resources/information_about_target_words_with_links.csv
navec_news_v1_1B_250K_300d_100q: resources/navec_news_v1_1B_250K_300d_100q.tar
slovnet_syntax_news_v1: resources/slovnet_syntax_news_v1.tar
article_target_words_realation_info: resources/article_target_words_realation_info.txt
article_target_words_in_links_realation_info: resources/article_target_words_in_links_realation_info.txt