base_url: http://www.consultant.ru/
articles_info_file: resources/articles_info.csv
model_info_file: resources/212.zip
articles_vectors_info_file: resources/articles_vectors_info_file_with_words.csv
articles_frequency_info_file: resources/articles_frequency_info_file.csv
articles_frequency_info_file_with_constraint: resources/articles_frequency_info_file_with_constraint.csv
articles_unique_words_analysis_file: resources/articles_unique_words_analysis_file.csv
articles_unique_words_analysis_file_with_frequency: resources/articles_unique_words_analysis_file_with_frequency.csv
most_popular_words_analysis_file: resources/most_popular_words_analysis_file.csv
unique_words_in_articles_analysis_file: resources/unique_words_in_articles_analysis_file.csv